#ifndef HLEDMATRIX_PRIVATE_H
#define HLEDMATRIX_PRIVATE_H

#define NUMBER_OF_ROWS 8
#define NUMBER_OF_COLS 8

#define DELAY_PER_FRAME 2500

u8 global_u8ArrayOfColPorts[NUMBER_OF_COLS] = {COL0PORT, COL1PORT, COL2PORT, COL3PORT, COL4PORT, COL5PORT, COL6PORT, COL7PORT};
u8 global_u8ArrayOfColPins[NUMBER_OF_COLS] = {COL0PIN, COL1PIN, COL2PIN, COL3PIN, COL4PIN, COL5PIN, COL6PIN, COL7PIN};

u8 global_u8ArrayOfRowPorts[NUMBER_OF_ROWS] = {ROW0PORT, ROW1PORT, ROW2PORT, ROW3PORT, ROW4PORT, ROW5PORT, ROW6PORT, ROW7PORT};
u8 global_u8ArrayOfRowPins[NUMBER_OF_ROWS] = {ROW0PIN, ROW1PIN, ROW2PIN, ROW3PIN, ROW4PIN, ROW5PIN, ROW6PIN, ROW7PIN};

#endif