#ifndef HLEDMATRIX_CFG_H
#define HLEDMATRIX_CFG_H

#define COL0PORT MGPIO_PORTB
#define COL1PORT MGPIO_PORTB
#define COL2PORT MGPIO_PORTB
#define COL3PORT MGPIO_PORTB
#define COL4PORT MGPIO_PORTA
#define COL5PORT MGPIO_PORTA
#define COL6PORT MGPIO_PORTA
#define COL7PORT MGPIO_PORTA

#define ROW0PORT MGPIO_PORTA
#define ROW1PORT MGPIO_PORTA
#define ROW2PORT MGPIO_PORTA
#define ROW3PORT MGPIO_PORTA
#define ROW4PORT MGPIO_PORTA
#define ROW5PORT MGPIO_PORTA
#define ROW6PORT MGPIO_PORTA
#define ROW7PORT MGPIO_PORTA

#define COL0PIN 12
#define COL1PIN 10
#define COL2PIN 9
#define COL3PIN 8
#define COL4PIN 11
#define COL5PIN 10
#define COL6PIN 9
#define COL7PIN 8

#define ROW0PIN 7
#define ROW1PIN 6
#define ROW2PIN 5
#define ROW3PIN 4
#define ROW4PIN 3
#define ROW5PIN 2
#define ROW6PIN 1
#define ROW7PIN 0

#endif